export const BOOKMARKS_LIST_REQUEST = "BOOKMARKS_LIST_REQUEST";
export const BOOKMARKS_LIST_SUCCESS = "BOOKMARKS_LIST_SUCCESS";
export const BOOKMARKS_LIST_FAIL = "BOOKMARKS_LIST_FAIL";

export const BOOKMARKS_CREATE_REQUEST = "BOOKMARKS_CREATE_REQUEST";
export const BOOKMARKS_CREATE_SUCCESS = "BOOKMARKS_CREATE_SUCCESS";
export const BOOKMARKS_CREATE_FAIL = "BOOKMARKS_CREATE_FAIL";

export const BOOKMARKS_DELETE_REQUEST = "BOOKMARKS_DELETE_REQUEST";
export const BOOKMARKS_DELETE_SUCCESS = "BOOKMARKS_DELETE_SUCCESS";
export const BOOKMARKS_DELETE_FAIL = "BOOKMARKS_DELETE_FAIL";
