export const RECOMMENDATIONS_LIST_REQUEST = "RECOMMENDATIONS_LIST_REQUEST";
export const RECOMMENDATIONS_LIST_SUCCESS = "RECOMMENDATIONS_LIST_SUCCESS";
export const RECOMMENDATIONS_LIST_FAIL = "RECOMMENDATIONS_LIST_FAIL";

export const RECOMMENDATIONS_LISTALL_REQUEST = "RECOMMENDATIONS_LISTALL_REQUEST";
export const RECOMMENDATIONS_LISTALL_SUCCESS = "RECOMMENDATIONS_LISTALL_SUCCESS";
export const RECOMMENDATIONS_LISTALL_FAIL = "RECOMMENDATIONS_LISTALL_FAIL";

export const RECOMMENDATIONS_CREATE_REQUEST = "RECOMMENDATIONS_CREATE_REQUEST";
export const RECOMMENDATIONS_CREATE_SUCCESS = "RECOMMENDATIONS_CREATE_SUCCESS";
export const RECOMMENDATIONS_CREATE_FAIL = "RECOMMENDATIONS_CREATE_FAIL";

export const RECOMMENDATIONS_UPDATE_REQUEST = "RECOMMENDATIONS_UPDATE_REQUEST";
export const RECOMMENDATIONS_UPDATE_SUCCESS = "RECOMMENDATIONS_UPDATE_SUCCESS";
export const RECOMMENDATIONS_UPDATE_FAIL = "RECOMMENDATIONS_UPDATE_FAIL";

export const RECOMMENDATIONS_DELETE_REQUEST = "RECOMMENDATIONS_DELETE_REQUEST";
export const RECOMMENDATIONS_DELETE_SUCCESS = "RECOMMENDATIONS_DELETE_SUCCESS";
export const RECOMMENDATIONS_DELETE_FAIL = "RECOMMENDATIONS_DELETE_FAIL";

export const RECOMMENDATIONS_USER_REQUEST = "RECOMMENDATIONS_USER_REQUEST";
export const RECOMMENDATIONS_USER_SUCCESS = "RECOMMENDATIONS_USER_SUCCESS";
export const RECOMMENDATIONS_USER_FAIL = "RECOMMENDATIONS_USER_FAIL";
